# Generated by Django 2.1.7 on 2019-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('score', models.CharField(max_length=3)),
                ('materialeasy', models.CharField(max_length=500)),
                ('materialmed', models.CharField(max_length=500)),
                ('materialhard', models.CharField(max_length=500)),
            ],
        ),
    ]
