# Generated by Django 2.1.7 on 2019-04-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_newassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
