# Generated by Django 2.1.7 on 2019-04-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_auto_20190421_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewAssignment',
            new_name='assignment',
        ),
    ]
