# Generated by Django 2.1.7 on 2019-04-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_auto_20190421_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='desc',
            new_name='description',
        ),
    ]
