# Generated by Django 2.1.5 on 2019-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_auto_20190421_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignmentRation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy', models.CharField(max_length=1)),
                ('med', models.CharField(max_length=1)),
                ('hard', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='shardCal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
